name: action di Sacchetti

on:
  push:

jobs: 
  ciao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            sacchetti
            test_app.py
            app.py

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install --upgrade pip
      - run: pip install scikit-learn joblib pandas optuna xgboost category_encoders flask pytest

      - name: Run training script
        run: python heart.py
        working-directory: sacchetti

      - uses: actions/upload-artifact@v4
        with:
          name: heartDiseasePrediction-w.0.0.1-RC
          path: sacchetti/bestHeartPred.joblib


  infer:
    runs-on: ubuntu-latest
    needs: ciao  # Questo dice che deve aspettare "ciao"

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            sacchetti
            test_app.py
            app.py

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install --upgrade pip
      - run: pip install flask pytest pandas joblib scikit-learn category_encoders

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: heartDiseasePrediction-w.0.0.1-RC
          path: sacchetti  # Scarica nella cartella dove l'API lo cerca

      - name: Run tests with pytest
        run: pytest
